platform :ios, '7.0' # 保持7.0, 编译的时候少报点Deprecated, 提高速度

pod 'CTAssetsPickerController'
pod 'DateTools'
pod 'EAIntroView'
pod 'FontAwesomeKit'
pod 'FormatterKit'
pod 'M13ProgressSuite'
pod 'RestKit'
pod 'SDWebImage'
pod 'SZTextView'
pod 'TLYShyNavBar'
pod 'TSMessages'
pod 'WeiboSDK'
pod 'Weixin'
