platform :ios, '8.0'

pod 'CTAssetsPickerController'
pod 'DateTools'
pod 'EAIntroView'
pod 'FontAwesomeKit'
pod 'FormatterKit'
pod 'M13ProgressSuite'
pod 'RestKit'
pod 'SDWebImage'
pod 'SZTextView'
pod 'TLYShyNavBar'
pod 'TSMessages'
pod 'WeiboSDK'
pod 'Weixin'
